Integration specs and n+1 problems
kazim110/my_blog pull request #8
Opened 2024-02-01 17:25 UTC by kazim110

### Summary
This pull request addresses the N+1 query problem within the application by implementing eager loading for users and posts. Additionally, it introduces Capybara specs to ensure proper testing and functionality verification.
### Changes Made

- Implemented eager loading for users and posts to resolve the N+1 query problem.
- Introduced Capybara specs to cover user and post-related functionalities.
- Added necessary tests to validate the behavior of users and posts.

### Pull Request Checklist

-  Implemented eager loading for users and posts.
-  Added Capybara specs for thorough testing.
-  Ensured all tests pass successfully.
-  Updated relevant documentation or comments regarding changes made.

### Testing Details

- Capybara specs have been added to thoroughly test user and post functionalities.
- Test cases cover scenarios related to users, posts, comments, and likes.

2024-02-01 20:11 UTC, prolajumokeoni requested changes
Hi @kazim110 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ N+1 problem solved
✔️ capybara gem is used



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- It would be nice to remove test files in your `requests` folder that are not passing as they are not needed for this milestone 👍🏿


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-01 20:11 UTC, prolajumokeoni commented on spec/integrations/users_show_spec.rb
> +  end
- [ ] Good job so far you are missing the `Tests that redirects to the user's post's index page when you click on a see all posts.` please add it 👍🏿

2024-02-01 20:11 UTC, prolajumokeoni commented on spec/integrations/users_show_spec.rb
> +  end
- [ ] It would be nice to seperate the tests you grouped here into different test cases and add their individual description, this will make your code readable  and you can determine which test is failing 👍🏿

2024-02-01 20:11 UTC, prolajumokeoni commented on spec/integrations/posts_index_spec.rb
> +  end
- [ ] Kindly separate the test cases, please add the description separately for each of the test cases this will help the next reviewer see that all test cases have been covered 👍🏿 

* Tests that asserts you can see the user's profile picture.
* Tests that asserts you can see the user's username.
* Tests that asserts you can see the number of posts the user has written.
* Tests that asserts you can see a post's title.
* Tests that asserts you can see some of the post's body.
* Tests that asserts you can see the first comments on a post.
* Tests that asserts you can see how many comments a post has.
* Tests that asserts you can see how many likes a post has.
* Tests that asserts you can see a section for pagination if there are more posts than fit on the view.
* Tests that redirects to the post's show page when you click on a post.

2024-02-01 20:11 UTC, prolajumokeoni commented on spec/integrations/posts_show_spec.rb
> +    expect(page).to have_content('This is the content of the post')
- [ ]  Kindly separate the test cases, please add the description separately for each of the test cases  👍🏿

2024-02-02 07:02 UTC, kazim110 commented on spec/integrations/users_show_spec.rb
> +  end
I have that test before this part of the test

2024-02-02 08:15 UTC, Efiamotu-1 requested changes
Hi @team, 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

- [ ] The required changes have been mentioned in the frontend pull request

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-02 08:15 UTC, Efiamotu-1 commented on spec/integrations/posts_show_spec.rb
- [ ] As requested by the previous reviewer in this [review link](https://github.com/kazim110/my_blog/pull/8#discussion_r1475060405) you are still missing some test cases which i have pointed out using the arrows in the image below, please kindly add them appropriately and accordingly so your project can be approved. :+1: :sparkles: 
![miss](https://github.com/kazim110/my_blog/assets/89055502/cdd19313-2aea-41c9-a171-e7536028b128)

2024-02-02 14:15 UTC, tugsem commented
## STATUS: APPROVED 👍🎯  
Hello @kazim110 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⭐ 
✔️ requested tests have been added 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-02 14:41 UTC, merged